name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up go
        uses: actions/setup-go@v2-beta
        with:
          go-version: '1.14'
      - name: Set up go env
        run: |
          echo "::set-env name=GOPATH::$(go env GOPATH)"
          echo "::add-path::$(go env GOPATH)/bin"
        shell: bash
      - name: Install jq
        run: |
          mkdir -p deps/bin
          curl -s -L -o deps/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
          chmod +x deps/bin/jq
          echo "::add-path::${PWD}/deps/bin"
      - name: Test
        run: make test
      - name: Build
        run: |
          make build-linux
          make package-linux
      - uses: actions/upload-artifact@v2
        with:
          name: lifecycle-linux-x86-64
          path: out/lifecycle-v*+linux.x86-64.tgz
  test-and-build-windows:
    runs-on: windows-latest
    steps:
      - name: Set git to use LF and symlinks
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          git config --global core.symlinks true
      - uses: actions/checkout@v2
      - name: Test
        run: |
          make docker-run-windows DOCKER_CMD="make test"
        shell: cmd
      - name: Build
        run: |
          make docker-run-windows DOCKER_CMD="make build-windows package-windows"
        shell: cmd
      - uses: actions/upload-artifact@v2
        with:
          name: lifecycle-windows-x86-64
          path: out/lifecycle-v*+windows.x86-64.tgz
